spring.application.name=SchemaFlow

spring.datasource.url=jdbc:postgresql://localhost:5432/parcial1_SW
spring.datasource.username=postgres
spring.datasource.password=6784
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false
