spring.application.name=SchemaFlow

spring.datasource.url=jdbc:postgresql://localhost:5432/diagramador
spring.datasource.username=postgres
spring.datasource.password=6784
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

api.gemini.key=AIzaSyCifr1H8o3wJ-QAaH-79GKdNsDHBc-jcbQ
api.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent