spring.application.name=SchemaFlow

spring.datasource.url=jdbc:postgresql://localhost:5432/diagramador
spring.datasource.username=postgres
spring.datasource.password=6784
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

# Gemini API Configuration
api.gemini.key=AIzaSyCifr1H8o3wJ-QAaH-79GKdNsDHBc-jcbQ
api.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent
api.gemini.model=gemini-1.5-pro

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0